// actionTypes.js
const types = {

  //contants
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  // Category
  FETCH_CATEGORY_REQUEST: 'FETCH_CATEGORY_REQUEST',
  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_ERROR: 'FETCH_CATEGORY_ERROR',
  CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',

  // Product
  FETCH_PRODUCT_BEST_SALE_SUCCESS: 'FETCH_PRODUCT_BEST_SALE_SUCCESS',
  FETCH_PRODUCT_BY_ID_CATEGORY_SUCCESS: 'FETCH_PRODUCT_BY_ID_CATEGORY_SUCCESS',
  FETCH_ALL_COMBO_SUCCESS: 'FETCH_ALL_COMBO_SUCCESS',
  FETCH_ALL_COMBO_FAILURE: 'FETCH_ALL_COMBO_FAILURE',
  FETCH_ALL_DRINK_SUCCESS: 'FETCH_ALL_DRINK_SUCCESS',
  FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',

  FETCH_PRODUCT_BY_ID_SUCCESS: 'FETCH_PRODUCT_BY_ID_SUCCESS',
  FETCH_PRODUCT_BY_ID_FAILURE: 'FETCH_PRODUCT_BY_ID_FAILURE',
  FETCH_COMBO_BY_ID_SUCCESS: 'FETCH_COMBO_BY_ID_SUCCESS',
  FETCH_PRODUCT_BY_ID_STORE_SUCCESS: 'FETCH_PRODUCT_BY_ID_STORE_SUCCESS',
  FETCH_RATING_PRODUCT_BY_ID_SUCCESS: 'FETCH_RATING_PRODUCT_BY_ID_SUCCESS',
  FETCH_PRODUCT_BY_SEARCH_QUERY_SUCCESS: 'FETCH_PRODUCT_BY_SEARCH_QUERY_SUCCESS',
  CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
  // Reset combo detail
  RESET_COMBO_DETAIL: 'RESET_COMBO_DETAIL',
  // user
  FETCH_PRODUCT_CART_SUCCESS: 'FETCH_PRODUCT_CART_SUCCESS',
  INCREASE_ITEM_QUANTITY: 'INCREASE_ITEM_QUANTITY',
  DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY',

};

export default types;
