// actionTypes.js
const types = {
  // Category
  FETCH_CATEGORY_REQUEST: 'FETCH_CATEGORY_REQUEST',
  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_ERROR: 'FETCH_CATEGORY_ERROR',
  CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
  CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',

  // Product
  FETCH_PRODUCT_BEST_SALE_SUCCESS: 'FETCH_PRODUCT_BEST_SALE_SUCCESS',
  FETCH_PRODUCT_BY_ID_CATEGORY_SUCCESS: 'FETCH_PRODUCT_BY_ID_CATEGORY_SUCCESS',
  FETCH_ALL_COMBO_SUCCESS: 'FETCH_ALL_COMBO_SUCCESS',
  FETCH_ALL_DRINK_SUCCESS: 'FETCH_ALL_DRINK_SUCCESS',
  FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
  FETCH_PRODUCT_BY_ID_SUCCESS: 'CCESS',
  FETCH_COMBO_BY_ID_SUCCESS: 'FETCH_COMBO_BY_ID_SUCCESS',
  FETCH_PRODUCT_BY_ID_STORE_SUCCESS: 'FETCH_PRODUCT_BY_ID_STORE_SUCCESS',
  FETCH_RATING_PRODUCT_BY_ID_SUCCESS: 'FETCH_RATING_PRODUCT_BY_ID_SUCCESS',
  FETCH_PRODUCT_BY_SEARCH_QUERY_SUCCESS: 'FETCH_PRODUCT_BY_SEARCH_QUERY_SUCCESS',
  CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',

};

export default types;
